tasks
Ja0nix/JS_base pull request #5
Opened 2021-03-11 11:07 UTC by Ja0nix

2021-03-14 21:10 UTC, Om1X requested changes

2021-03-14 21:10 UTC, Om1X commented on lesson5.js
> +};
функция должна быть методом объекта корзины.

2021-03-14 21:10 UTC, Om1X commented on lesson5.js
> +  };
аналогично. А также замените генерацию разметки через document.createElement на insertAdjacentHTML

2021-03-15 09:49 UTC, Ja0nix commented on lesson5.js
> +  };
Исправила оба замечания

2021-03-15 09:50 UTC, merged